# -*- coding: utf-8 -*-
"""Overview and Cleansing Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPhDe5PpdCkGshQrRewHenmxLzYsDmVa
"""

pip install pandas

pip install tabulate

from google.colab import files


uploaded = files.upload()

"""Overview Data"""

# Read data from CSV file
import numpy as np
import pandas as pd
from tabulate import tabulate

filename = 'SampleSuperstore.csv'
data = pd.read_csv (filename)

# Display the DataFrame in a table format
print(tabulate(data, headers='keys', tablefmt='psql'))

"""Data Cleansing

"""

# Data cleansing: removing 'Postal Code' and 'Region' columns
data_cleaned = data.drop(columns=['Postal Code', 'Region'])

# Display the cleaned DataFrame
print("Cleaned Data:")
display(data_cleaned)

